# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 CARLOS Contributors
# GENERATED by scripts/migration/o19/generate_manifests.py — DO NOT EDIT.
# Curation lives in scripts/migration/o19/overrides_schema.py /
# overrides_props.py; edit those and regenerate.

"""OSCAR 19 -> CARLOS properties manifest."""

PROPS_MAP_VERSION = 'o19map-2+47eba883'

# active keys of the stock O19 oscar_mcmaster.properties — the baseline-diff
# reference: clinic keys equal to these defaults are ignored (CARLOS defaults win)
O19_DEFAULTS = {
    'ALLOW_UPDATE_DOCUMENT_CONTENT': 'false',
    'ALT_DISCHARGE_REASON': 'no',
    'AUTO_GENERATE_PROVIDER_NO': 'no',
    'AdtA09Handler.CHECK_IN_EARLY_ALLOWANCE': '4',
    'AdtA09Handler.CHECK_IN_LATE_ALLOWANCE': '2',
    'BILLING_REVIEW_AUTO_PAYMENT': 'no',
    'BILLING_SUPERUSER': '999998',
    'CASELOAD_DEFAULT_ALL_PROVIDERS': 'false',
    'CASEMANAGEMENT': 'all',
    'CBI_JOB_INTERVAL': '43200000',
    'CBI_REMINDER_WINDOW': 'no',
    'CBI_REMIND_ON_UPDATE_DEMOGRAPHIC': 'false',
    'CBI_WS_CLIENT_QNAME': 'CBIServiceImplService',
    'CBI_WS_CLIENT_QNAME_URL': 'http://ws.cbi.com/',
    'CBI_WS_URL': 'https://ws.cbiproject.ca:8443/CBIService/cbitest?wsdl',
    'CMESort': 'UP',
    'COMMUNITY_ISSUE_CODETYPE': 'icd10',
    'CONSULTATION_APPOINTMENT_INSTRUCTIONS_LOOKUP': 'true',
    'CONSULTATION_AUTO_INCLUDE_ALLERGIES': 'true',
    'CONSULTATION_AUTO_INCLUDE_MEDICATIONS': 'true',
    'CONSULTATION_LOCK_REFERRAL_DATE': 'true',
    'CONSULTATION_PATIENT_WILL_BOOK': 'false',
    'DATE_FORMAT': 'yyyy-MM-dd',
    'DEMOGRAPHIC_CONTACT.AllowInternalHCP': 'true',
    'DEMOGRAPHIC_CONTACT.ShowProgramRestriction': 'false',
    'DEMOGRAPHIC_CONTACT_OTHER': 'true',
    'DEMOGRAPHIC_CONTACT_PERSONAL': 'true',
    'DEMOGRAPHIC_PATIENT_CLINIC_STATUS': 'true',
    'DEMOGRAPHIC_PATIENT_HEALTH_CARE_TEAM': 'true',
    'DEMOGRAPHIC_PATIENT_ROSTERING': 'true',
    'DEMOGRAPHIC_WAITING_LIST': 'true',
    'DOCUMENT_DOWNLOAD_METHOD': 'stream',
    'DOC_FORWARD': '/dms/complete.jsp',
    'DX_QUICK_LIST_BILLING_REVIEW': 'yes',
    'DX_QUICK_LIST_DEFAULT': 'Chronic Diseases',
    'EA_FORWORD': '/billing/CA/ON/billingEAreport.jsp',
    'ECHART_SIGN_LINE': '[${oscarEncounter.class.EctSaveEncounterAction.msgSigned} ${DATE} ${oscarEncounter.class.EctSaveEncounterAction.msgSigBy} ${USERSIGNATURE}]\n',
    'ECHART_VERSIGN_LINE': '[${oscarEncounter.class.EctSaveEncounterAction.msgVerAndSig} ${DATE} ${oscarEncounter.class.EctSaveEncounterAction.msgSigBy} ${USERSIGNATURE}]\n',
    'ENABLE_CONFORMANCE_ONLY_FEATURES': 'false',
    'ENABLE_PREVENTION_BILLING': 'false',
    'ENCOUNTER_TIME_MANDATORY': 'false',
    'FILTER_ON_FACILITY': 'false',
    'FIRST_NATIONS_MODULE': 'false',
    'FORMS_PROMOTEXT': 'Created by: OSCAR The open-source EMR www.oscarcanada.org',
    'GET_OHIP_INFO': 'yes',
    'HELP_SEARCH_URL': 'http://www.oscarmanual.org/search?SearchableText=%s',
    'HL7TEXT_LABS': 'no',
    'HL7_A04_GENERATION': 'false',
    'HL7_A04_TRANSPORT_ADDR': '127.0.0.1',
    'HL7_A04_TRANSPORT_PORT': '3987',
    'IGNORE_PASSWORD_REQUIREMENTS': 'false',
    'IMMUNIZATION_IN_PREVENTION': 'yes',
    'INCOMINGDOCUMENT_DIR': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/incomingdocs',
    'INCOMINGDOCUMENT_RECYCLEBIN': 'true',
    'INTEGRATOR_COMPRESSION_ENABLED': 'false',
    'INTEGRATOR_FORCE_FULL': 'yes',
    'INTEGRATOR_LOGGING_ENABLED': 'false',
    'INTEGRATOR_SLEEP_ON_ERROR': '300000',
    'INTEGRATOR_THROTTLE_DELAY': '100',
    'INTEGRATOR_UPDATE_PERIOD': '43200000',
    'INVOICE_DIR': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/billing/invoices',
    'IS_PIN_ENCRYPTED': 'no',
    'LAB_NOMATCH_NAMES': 'yes',
    'MYDRUGREF_DS': 'yes',
    'MYOSCAR_SYMPTOM_CHECKLIST_REPORT_TEMPLATE_NAME': 'Symptom Checklist',
    'MY_OSCAR': 'no',
    'MY_OSCAR_EXCHANGE_INTERVAL': '5',
    'NEW_BC_TELEPLAN': 'yes',
    'NEW_CONTACTS_UI': 'false',
    'NEW_CONTACTS_UI_EXTERNAL_CONTACT': 'false',
    'NEW_USER_PIN_CONTROL': 'yes',
    'OLIS_PROCESSING_ID': 'P',
    'OMD_HRM_AUTH_KEY_FILENAME': 'mcmu_sk.ppk',
    'OMD_HRM_IP': '207.219.74.198',
    'OMD_HRM_PORT': '22',
    'OMD_HRM_REMOTE_DIR': 'Test',
    'ONEDT_ARCHIVE': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/onEDTDocs/archive/',
    'ONEDT_INBOX': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/onEDTDocs/inbox/',
    'ONEDT_OUTBOX': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/onEDTDocs/outbox/',
    'ONEDT_SENT': '/usr/local/tomcat/webapps/OscarDocument/oscar_mcmaster/onEDTDocs/sent/',
    'ORN_PILOT': 'no',
    'PGP_BIN': '/usr/bin/pgpgpg',
    'PGP_CMD': '-e',
    'PGP_ENV': 'GNUPGHOME=/usr/local/gnupg/',
    'PREVENTION': 'yes',
    'PREVENTION_CLASSIC_VIEW': 'no',
    'QR_CODE_ENABLED_PROVIDER_DEFAULT': 'false',
    'QR_CODE_ERROR_CORRECTION_LEVEL': 'H',
    'QR_CODE_IMAGE_SCALE_FACTOR': '2',
    'RA_FORWORD': '/billing/CA/ON/genRA.jsp',
    'RENAL_DOSING_DS': 'yes',
    'RX3': 'yes',
    'RXFAX': 'yes',
    'RX_ALLERGY_CHECKING': 'yes',
    'RX_INTERACTION_LOCAL_DRUGREF_REGIONAL_IDENTIFIER': 'no',
    'SHOW_FILE_IMPORT_SEARCH': 'yes',
    'SHOW_PREVENTION_STOP_SIGNS': 'false',
    'SINGLE_PAGE_CHART': 'false',
    'SOB_CHECKALL': 'yes',
    'SUPERUSER': 'oscardoc',
    'Support_Contact': 'Jay Gallagher (905-525-9140 ext28517, jay@jayweb.ca)',
    'TA_FORWARD': '/billing/CA/BC/genTA.jsp',
    'TESTING': 'yes',
    'TIME_FORMAT': 'HH:mm:ss',
    'TOMCAT_KEYSTORE_FILE': '/home/oscar/ihe/ihe.keystore.jks',
    'TOMCAT_TRUSTSTORE_FILE': '/home/oscar/ihe/ihe.truststore.jks',
    'TORONTO_RFQ': 'no',
    'TRANSPORTATION_TIME_MANDATORY': 'false',
    'USE_CAISI_LOGO': 'true',
    'USE_NEW_ECHART': 'yes',
    'USE_NEW_PATIENT_CONSENT_MODULE': 'true',
    'VMSTAT_LOGGING_PERIOD': '900000',
    'Vendor_Product': 'OSCARMcMaster, OSCARMcMaster ver11',
    'WCB_FORM_REQUIRED_CODES': '19937,19938,19939,19940,19941,19943,19944,19167,19173,19174,19175,19134,19135',
    'WKHTMLTOPDF_ARGS': '--print-media-type',
    'WKHTMLTOPDF_COMMAND': 'wkhtmltopdf-i386',
    'admin.hph': 'false',
    'allowMultipleSameDayGroupAppt': 'yes',
    'appointment_locking_timeout': '0',
    'appt_formTbl': '',
    'appt_intake_form': 'off',
    'backup_path': '/home/mysql/',
    'billcenter': 'G',
    'billregion': 'ON',
    'born18m_eform_ndds': 'Nipissing District Developmental Screen',
    'born18m_eform_report18m': 'Summary Report: 18-month Well Baby Visit',
    'born18m_eform_rourke': 'Rourke Baby Record',
    'born18m_env': 'T',
    'born18m_job_provider': '999998',
    'born18m_orgcode': 'mcmaster',
    'born18m_sftp_host': 'ftp.test.com',
    'born18m_sftp_port': '22',
    'born18m_sftp_remote_dir': '/',
    'born18m_upload_hour': '01',
    'born_eform_ndds12m': 'NDDS 12 Months',
    'born_eform_ndds15m': 'NDDS 15 Months',
    'born_eform_ndds18m': 'NDDS 18 Months',
    'born_eform_ndds1m2m': 'NDDS 1&2 Months',
    'born_eform_ndds24m': 'NDDS 24 Months',
    'born_eform_ndds30m': 'NDDS 30 Months',
    'born_eform_ndds3y': 'NDDS 3 Years',
    'born_eform_ndds4m': 'NDDS 4 Months',
    'born_eform_ndds4y': 'NDDS 4 Years',
    'born_eform_ndds5y': 'NDDS 5 Years',
    'born_eform_ndds6m': 'NDDS 6 Months',
    'born_eform_ndds6y': 'NDDS 6 Years',
    'born_eform_ndds9m': 'NDDS 9 Months',
    'born_eform_rourke': 'Rourke Baby Record',
    'born_eform_sumrptmarkers': 'Summary Report: Well Baby Visit',
    'born_env': 'T',
    'born_orgcode': 'mcmaster',
    'born_scheduler_job_run_as_provider': '999998',
    'born_sftp_host': 'ftp.test.com',
    'born_sftp_port': '22',
    'born_sftp_remote_dir': '/',
    'buildDateTime': '${build.dateTime}',
    'buildtag': '${build.JOB_NAME}-${build.BUILD_NUMBER}',
    'caisi.cds.restrict_by_program_domain': 'false',
    'caisi.new_client.strict_search': 'false',
    'caisi.registration_intake.updateMRPOnSave': 'true',
    'caisi.search.workflow': 'true',
    'casemgmt.note.password.enabled': 'true',
    'ckd_notification_scheme': 'tickler',
    'clientdropbox': 'off',
    'clinic_no': '3821',
    'clinic_view': '3866',
    'clinicaid_domain': 'https://demo.clinicaid.ca',
    'clinicaid_instance_name': 'oscar_demo',
    'cobalt': 'no',
    'confidentiality_statement.v1': 'This document may contain personal health information.  Please consider confidentiality when distributing or disposing of this document.',
    'confidentiality_statement.v2': 'Personal Health Information: CONFIDENTIAL',
    'consultation_dynamic_labelling_enabled': 'false',
    'consultation_fax_enabled': 'false',
    'consultation_indivica_attachment_enabled': 'false',
    'consultation_signature_enabled': 'true',
    'contact.required.program': 'false',
    'cr_security': 'off',
    'dataCenterId': '00000',
    'db_driver': 'com.mysql.jdbc.Driver',
    'db_log_abandoned': 'true',
    'db_max_active': '32',
    'db_max_idle': '8',
    'db_max_wait': '20000',
    'db_name': 'oscar_mcmaster?zeroDateTimeBehavior=round&useOldAliasMetadataBehavior=true&jdbcCompliantTruncation=false',
    'db_remove_abandoned': 'true',
    'db_remove_abandoned_timeout': '15',
    'db_type': 'mysql',
    'db_uri': 'jdbc:mysql:///',
    'db_validationQuery': 'select 1',
    'default_bill_center': '',
    'default_search_mode': 'search_name',
    'default_view': 'MFP',
    'displayAlertsOnScheduleScreen': 'false',
    'displayNotesOnScheduleScreen': 'false',
    'documentUploader.maxNumberOfFiles': '5',
    'drugref_route': 'topical,intravenous,disinfectant',
    'drugref_route_search': 'off',
    'drugref_url': 'http://67.69.12.116:8001',
    'dxResearch_coding_sys': 'icd9,ichppccode',
    'eaaps.enabled': 'false',
    'eform_fax_enabled': 'false',
    'eform_generator_indivica_fax_enabled': 'false',
    'eform_generator_indivica_print_enabled': 'false',
    'eform_generator_indivica_signature_enabled': 'false',
    'eform_signature_enabled': 'false',
    'email.connection_security': 'ssl',
    'email.host': 'localhost',
    'email.port': '25',
    'email.protocol': 'smtp',
    'enable_create_child_record': 'false',
    'enable_rx_custom_methodone_suboxone': 'false',
    'enable_rx_watermark': 'false',
    'enable_wait_list_email_notifications': 'false',
    'faxEnable': 'no',
    'faxIdentifier': 'zwf4t%8*9@s',
    'faxKeystore': '/root/oscarFax/oscarFax.keystore',
    'faxLogo': '',
    'faxPollInterval': '5000',
    'faxURI': 'https://67.69.12.117:14043/OSCARFaxWebService',
    'form_intake_program_access_fid': '1',
    'form_intake_program_access_service_id': '10016',
    'form_intake_program_cash_fid': '1',
    'form_intake_program_cash_service_id': '10016',
    'groupModuleEnabled': 'false',
    'hcv.logging.skip': 'true',
    'hcv.service.id': '010637',
    'hcv.service.url': 'https://ws.conf.ebs.health.gov.on.ca:1440/HCVService/HCValidationService',
    'hcv.type': 'simple',
    'health_tracker': 'false',
    'hibernate.dialect': 'org.oscarehr.util.persistence.OscarMySQL5Dialect',
    'hibernate.generate_statistics': 'false',
    'hibernate.show_sql': 'false',
    'hl7_a04_build_dir': '/var/lib/adt/',
    'hl7_a04_fail_dir': '/var/lib/adt/failed/',
    'host': '127.0.0.1',
    'hsfo_job_run_as_provider': '999998',
    'inPatient': 'no',
    'inactive_statuses': "'IN','DE','IC','ID','MO','FI'",
    'indivica_hc_read_enabled': 'false',
    'indivica_rich_text_letter_enabled': 'false',
    'invoice_head_logo_doctype': 'invoice letterhead',
    'invoice_reports.print.hide_name': 'false',
    'isNewONbilling': 'true',
    'l7_a04_sent_dir': '/var/lib/adt/sent/',
    'lab.handler.ALPHA.enabled': 'true',
    'lab.handler.BIOTEST.enabled': 'false',
    'lab.handler.CLS.enabled': 'false',
    'lab.handler.CML.enabled': 'true',
    'lab.handler.EPSILON.enabled': 'false',
    'lab.handler.GDML.enabled': 'true',
    'lab.handler.HHSEMR.enabled': 'false',
    'lab.handler.HRMXML.enabled': 'true',
    'lab.handler.ICL.enabled': 'false',
    'lab.handler.IHA.enabled': 'false',
    'lab.handler.MDS.enabled': 'true',
    'lab.handler.MEDITECH.enabled': 'true',
    'lab.handler.MEDVUE.enabled': 'false',
    'lab.handler.OLIS_HL7.enabled': 'true',
    'lab.handler.ORU_R01.enabled': 'false',
    'lab.handler.OSCAR_TO_OSCAR_HL7_V2.enabled': 'false',
    'lab.handler.OTHER.enabled': 'true',
    'lab.handler.OUL_R21.enabled': 'false',
    'lab.handler.PATHL7.enabled': 'false',
    'lab.handler.PDFDOC.enabled': 'false',
    'lab.handler.PFHT.enabled': 'false',
    'lab.handler.SIOUX.enabled': 'false',
    'lab.handler.Spire.enabled': 'false',
    'lab.handler.TDIS.enabled': 'true',
    'lab.handler.TRUENORTH.enabled': 'false',
    'lab_req_include_chartno': 'false',
    'label.1no': '1',
    'label.2no': '1',
    'label.3no': '1',
    'label.4no': '1',
    'label.5no': '1',
    'label.gap': '0',
    'label.height': '145',
    'label.left': '200',
    'label.top': '0',
    'labreq_CKD': 'false',
    'ldap.authMethod': 'simple',
    'ldap.authorization': 'false',
    'ldap.baseDn': 'CN=Roles,CN=Providers,DC=OSCAR,DC=ca',
    'ldap.enabled': 'false',
    'ldap.url': 'ldap://localhost:389',
    'log.purge.minDays': '3650',
    'log.purge.mysqldump': '/usr/bin/mysqldump',
    'login_local_ip': '192.168',
    'login_max_duration': '10',
    'login_max_failed_times': '3',
    'loginlogo': '',
    'logintext': '',
    'logintitle': '',
    'mandatory_password_reset': 'true',
    'mcedt.enabled': 'false',
    'mcedt.last.downloadedID.file': '.LastDownloadedID',
    'mcedt.logging.skip': 'false',
    'mcedt.mailbox.enabled': 'true',
    'mcedt.service.designated.ids': '',
    'mcedt.service.id': '',
    'mcedt.service.url': '',
    'moh_file_management_enabled': 'false',
    'mrp_model': 'yes',
    'multioffice.admin.role.name': 'admin',
    'multioffice.formalize.doctor.maximum.provider.id': '100',
    'multioffice.formalize.doctor.minimum.provider.id': '1',
    'multioffice.formalize.provider.id': 'false',
    'myOSCAR.url': 'https://kindredphr.com/',
    'mymeds_job_run_as_provider': '999998',
    'myoscar_server_base_url': 'https://maple.myoscar.org:8443/myoscar_server/ws',
    'new_flowsheet_enabled': 'false',
    'new_label_print': 'false',
    'olis_request_url': 'https://olis.ssha.ca/ssha.olis.webservices.ER7/OLIS.asmx',
    'olis_simulate': 'no',
    'onare_labreqver': '07',
    'ontariomd_cds_diabetes_link': 'https://www.ontariomd.ca/cms/xml/ontariomd_cds_diabetes.xsd',
    'orn_labreqver': '10',
    'oscarMeasurement_css': '/OscarDocument/oscar_mcmaster/oscarEncounter/oscarMeasurements/styles/',
    'oscarMeasurement_css_download_method': 'stream',
    'oscarMeasurements.orderGroupById': 'false',
    'oscar_myoscar_clinic_component_url': '',
    'oscar_myoscar_sync_component_url': '',
    'oscar_port': '8080',
    'osp.contactEmail': '<Not Set>',
    'osp.contactName': '<Not Set>',
    'osp.name': '<Not Set>',
    'osp.phone': '<Not Set>',
    'osp.url': '<Not Set>',
    'password.forcePasswordResetToUpdateStorage': 'true',
    'password.pastPasswordsToNotUse': '0',
    'password_group_digits': '0123456789',
    'password_group_lower_chars': 'abcdefghijklmnopqrstuvwxyz',
    'password_group_special': '! @#$%^&*()_+|~-=\\`{}[]:";\'<>?,./',
    'password_group_upper_chars': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'password_min_groups': '3',
    'password_min_length': '8',
    'password_pin_min_length': '4',
    'phoneprefix': '905-',
    'pmm.client.search.outside.of.domain.enabled': 'true',
    'pmm.refer.temporaryAdmission.enabled': 'true',
    'prenatal_screening_abbrv': 'IPS',
    'prenatal_screening_eform_group': 'IPS',
    'prenatal_screening_name': 'Integrated Prenatal Screening',
    'prevention_show_comments': 'false',
    'print.includeMRP': 'true',
    'print.useCurrentProgramInfoInHeader': 'false',
    'printPDF_referring_prac': 'no',
    'professionalContact.required.program': 'false',
    'professionalContact.required.workPhone': 'true',
    'program': 'on',
    'project_home': 'oscar_mcmaster',
    'receptionist_alt_view': 'no',
    'redirectstudysite_default_baseURL': 'http://competeii.mcmaster.ca/PDSsecurity/login.asp',
    'referral_menu': 'no',
    'refresh.appointmentprovideradminday.jsp': '180',
    'refresh.encounterLayout.jsp': '-1',
    'resource_base_url': 'http://oscarmanual.org/14/',
    'rma_enabled': 'false',
    'rx.allow_rerx': 'true',
    'rx.enable_internal_dispensing': 'false',
    'rx_enhance': 'false',
    'rx_fax_enabled': 'false',
    'rx_signature_enabled': 'true',
    'rx_strict_med_term': 'false',
    'save_as_xml': 'true',
    'schedule.groupsFromPrograms': 'false',
    'schedule_templatecode': 'true',
    'search.most_recent_on_empty': 'true',
    'search.searchName.addLeadingWildcard': 'false',
    'searchresults.showAddress': 'false',
    'seconds_till_considered_stale': '-1',
    'sharingcenter.enabled': 'false',
    'showBandNumberOnly': 'true',
    'showRxBandNumber': 'false',
    'showRxChartNo': 'false',
    'showSexualHealthLabel': 'false',
    'skip_postal_code_validation': 'false',
    'softwareCommonName': 'OSCAR',
    'softwareName': 'Open Source Clinical Application Resource',
    'spire_download_dir': '/var/lib/spire/labs/',
    'spire_server_hostname': 'hostname',
    'streethealth': 'yes',
    'tickler.default_sort_order': 'asc',
    'tickler_default_assigned_provider': 'false',
    'tickler_edit_enabled': 'false',
    'tickler_email_enabled': 'false',
    'tickler_email_provider_enabled': 'false',
    'tickler_email_provider_from_address': 'test@example.com',
    'tickler_email_provider_subject': 'OSCAR Tickler received',
    'tickler_warn_period': '1',
    'tomcat_path': '/usr/local/tomcat/',
    'useDemoClinicInfoOnInvoice': 'true',
    'use_lab_clientreference': 'false',
    'util.erx.clinic_facility_id': '123',
    'util.erx.clinic_locale': '2',
    'util.erx.clinic_training_mode': 'false',
    'util.erx.enabled': 'false',
    'util.erx.oscarerx_sso_url': 'https://www.zoommed.com/zrx/ZRxWebMobile/ProductSearch.aspx?',
    'util.erx.software': 'OSCAR',
    'util.erx.synchronize_interval': '86400000',
    'util.erx.vendor': 'McMaster University',
    'util.erx.version': '11',
    'util.erx.webservice_url': 'https://www.zoommed.com/zrx/ZRxPMISBridge/PMISBridge.asmx',
    'vendorBusinessName': 'McMaster University',
    'vendorCommonName': 'McMaster University',
    'vendorId': 'vendorId not set',
    'version': 'version not set',
    'versionDate': 'versionDate not set',
    'visit_type': 'Clinic Visit',
    'visitlocation': 'P1|PEMBERTON',
    'visittype': "O|Physician's office",
    'wait_list_email_notification_period': '86400000',
    'wait_list_email_notification_program_ids': '',
    'warnOnDeleteBill': 'false',
    'web_service_client.connection_timeout_ms': '1500',
    'web_service_client.received_timeout_ms': '3000',
    'wl_default_issue': 'false',
    'workflow_enhance': 'false',
    'ws_endpoint_url_base': 'https://127.0.0.1:8081/oscar',
}

# stock keys whose value is a credential: their defaults are deliberately not
# shipped — the props phase always surfaces these for review instead of
# baseline-diffing them
SECRET_DEFAULT_KEYS = [
    'CBI_WS_PASSWORD',
    'CBI_WS_USERNAME',
    'OMD_HRM_USER',
    'PGP_KEY',
    'TOMCAT_KEYSTORE_PASSWORD',
    'TOMCAT_TRUSTSTORE_PASSWORD',
    'born18m_sftp_password',
    'born18m_sftp_username',
    'born_sftp_password',
    'born_sftp_username',
    'clinicaid_api_key',
    'db_password',
    'db_username',
    'email.password',
    'email.username',
    'hcv.keystore.pass',
    'hcv.keystore.user',
    'hcv.service.conformanceKey',
    'hcv.service.pass',
    'hcv.service.user',
    'mcedt.keystore.pass',
    'mcedt.keystore.user',
    'mcedt.service.conformanceKey',
    'mcedt.service.pass',
    'mcedt.service.user',
    'redirectstudysite_default_password',
    'redirectstudysite_default_username',
    'spire_server_password',
    'spire_server_user',
    'util.erx.clinic_password',
    'util.erx.clinic_username',
]

# CARLOS's own default for the `carry` keys where it DIFFERS from the O19 default:
# the baseline diff leaves such a key untouched (CARLOS wins), which silently flips
# the clinic's behaviour at cutover unless the props report names it
CARLOS_DEFAULTS = {
    'CONSULTATION_AUTO_INCLUDE_ALLERGIES': 'false',
    'CONSULTATION_AUTO_INCLUDE_MEDICATIONS': 'false',
    'CONSULTATION_LOCK_REFERRAL_DATE': 'false',
    'DEMOGRAPHIC_PATIENT_HEALTH_CARE_TEAM': 'false',
    'ECHART_SIGN_LINE': '[${encounter.class.EctSaveEncounterAction.msgSigned} ${DATE} ${encounter.class.EctSaveEncounterAction.msgSigBy} ${USERSIGNATURE}]\n',
    'ECHART_VERSIGN_LINE': '[${encounter.class.EctSaveEncounterAction.msgVerAndSig} ${DATE} ${encounter.class.EctSaveEncounterAction.msgSigBy} ${USERSIGNATURE}]\n',
    'FORMS_PROMOTEXT': '',
    'HL7TEXT_LABS': 'yes',
    'NEW_CONTACTS_UI': 'true',
    'NEW_CONTACTS_UI_EXTERNAL_CONTACT': 'true',
    'confidentiality_statement.v1': 'The information transmitted is intended only for the person to whom it is addressed and may contain confidential, proprietary and/or privileged material. Any unauthorized review, distribution or other use of or the taking of any action in reliance upon this information is prohibited. The contents of this message may be subject to privilege and all rights to that privilege are expressly claimed and not waived. If you receive this in error, please contact the sender  and delete or destroy this message and any copies. Thank you.',
    'consultation_fax_enabled': 'true',
    'faxPollInterval': '60000',
    'save_as_xml': 'false',
}

# oscarResources bundle keys CARLOS renamed, verified against the CARLOS bundle:
# a `rewrite: bundle` value's ${...} tokens are remapped through this before the value
# is carried, and a token that is not a key here is refused (needs-review)
BUNDLE_KEY_RENAMES = {
    'oscarEncounter.class.EctSaveEncounterAction.msgLocked': 'encounter.class.EctSaveEncounterAction.msgLocked',
    'oscarEncounter.class.EctSaveEncounterAction.msgSigBy': 'encounter.class.EctSaveEncounterAction.msgSigBy',
    'oscarEncounter.class.EctSaveEncounterAction.msgSigned': 'encounter.class.EctSaveEncounterAction.msgSigned',
    'oscarEncounter.class.EctSaveEncounterAction.msgSplitChart': 'encounter.class.EctSaveEncounterAction.msgSplitChart',
    'oscarEncounter.class.EctSaveEncounterAction.msgVer': 'encounter.class.EctSaveEncounterAction.msgVer',
    'oscarEncounter.class.EctSaveEncounterAction.msgVerAndSig': 'encounter.class.EctSaveEncounterAction.msgVerAndSig',
}

KEYS = {
    'ALLOW_UPDATE_DOCUMENT_CONTENT': {
        'd': 'carry',
    },
    'ALT_DISCHARGE_REASON': {
        'd': 'dropped-flag',
    },
    'AUTO_GENERATE_PROVIDER_NO': {
        'd': 'carry',
    },
    'AdtA09Handler.CHECK_IN_EARLY_ALLOWANCE': {
        'd': 'dropped-flag',
    },
    'AdtA09Handler.CHECK_IN_LATE_ALLOWANCE': {
        'd': 'dropped-flag',
    },
    'BASE_DOCUMENT_DIR': {
        'd': 'deploy-owned',
    },
    'BILLING_REVIEW_AUTO_PAYMENT': {
        'd': 'carry',
    },
    'BILLING_SUPERUSER': {
        'd': 'carry',
    },
    'CASELOAD_DEFAULT_ALL_PROVIDERS': {
        'd': 'dropped-flag',
    },
    'CASEMANAGEMENT': {
        'd': 'carry',
    },
    'CMESort': {
        'd': 'carry',
    },
    'COMMUNITY_ISSUE_CODETYPE': {
        'd': 'carry',
    },
    'CONSULTATION_APPOINTMENT_INSTRUCTIONS_LOOKUP': {
        'd': 'carry',
    },
    'CONSULTATION_AUTO_INCLUDE_ALLERGIES': {
        'd': 'carry',
    },
    'CONSULTATION_AUTO_INCLUDE_MEDICATIONS': {
        'd': 'carry',
    },
    'CONSULTATION_LOCK_REFERRAL_DATE': {
        'd': 'carry',
    },
    'CONSULTATION_PATIENT_WILL_BOOK': {
        'd': 'carry',
    },
    'DATE_FORMAT': {
        'd': 'carry',
    },
    'DEMOGRAPHIC_PATIENT_CLINIC_STATUS': {
        'd': 'carry',
    },
    'DEMOGRAPHIC_PATIENT_HEALTH_CARE_TEAM': {
        'd': 'carry',
    },
    'DEMOGRAPHIC_PATIENT_ROSTERING': {
        'd': 'carry',
    },
    'DEMOGRAPHIC_WAITING_LIST': {
        'd': 'carry',
    },
    'DOCUMENT_DIR': {
        'd': 'deploy-owned',
    },
    'DOCUMENT_DOWNLOAD_METHOD': {
        'd': 'dropped-flag',
    },
    'DOC_FORWARD': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'DX_QUICK_LIST_BILLING_REVIEW': {
        'd': 'carry',
    },
    'DX_QUICK_LIST_DEFAULT': {
        'd': 'carry',
    },
    'EA_FORWORD': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'ECHART_SIGN_LINE': {
        'd': 'carry',
        'rewrite': 'bundle',
    },
    'ECHART_VERSIGN_LINE': {
        'd': 'carry',
        'rewrite': 'bundle',
    },
    'ENABLE_CONFORMANCE_ONLY_FEATURES': {
        'd': 'carry',
    },
    'ENABLE_PREVENTION_BILLING': {
        'd': 'carry',
    },
    'ENCOUNTER_TIME_MANDATORY': {
        'd': 'carry',
    },
    'FAX_INCOMING_DIR': {
        'd': 'deploy-owned',
    },
    'FILTER_ON_FACILITY': {
        'd': 'carry',
    },
    'FIRST_NATIONS_MODULE': {
        'd': 'carry',
    },
    'FORMS_PROMOTEXT': {
        'd': 'carry',
    },
    'GET_OHIP_INFO': {
        'd': 'carry',
    },
    'HELP_SEARCH_URL': {
        'd': 'dropped-flag',
    },
    'HL7TEXT_LABS': {
        'd': 'carry',
    },
    'HL7_A04_GENERATION': {
        'd': 'carry',
    },
    'HL7_A04_TRANSPORT_ADDR': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'HL7_A04_TRANSPORT_PORT': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'HOME_DIR': {
        'd': 'translate',
        't': 'docpath',
    },
    'IGNORE_PASSWORD_REQUIREMENTS': {
        'd': 'carry',
    },
    'IMMUNIZATION_IN_PREVENTION': {
        'd': 'carry',
    },
    'INCOMINGDOCUMENT_DIR': {
        'd': 'translate',
        't': 'docpath',
    },
    'INCOMINGDOCUMENT_RECYCLEBIN': {
        'd': 'carry',
    },
    'INVOICE_DIR': {
        'd': 'translate',
        't': 'docpath',
    },
    'IS_PIN_ENCRYPTED': {
        'd': 'carry',
    },
    'LAB_NOMATCH_NAMES': {
        'd': 'carry',
    },
    'NEW_BC_TELEPLAN': {
        'd': 'carry',
    },
    'NEW_CONTACTS_UI': {
        'd': 'carry',
    },
    'NEW_CONTACTS_UI_EXTERNAL_CONTACT': {
        'd': 'carry',
    },
    'NEW_USER_PIN_CONTROL': {
        'd': 'carry',
    },
    'OMD_HRM_AUTH_KEY_FILENAME': {
        'd': 'dropped-flag',
        'advisory': 'hrm',
    },
    'OMD_HRM_IP': {
        'd': 'dropped-flag',
        'advisory': 'hrm',
    },
    'OMD_HRM_PORT': {
        'd': 'dropped-flag',
        'advisory': 'hrm',
    },
    'OMD_HRM_REMOTE_DIR': {
        'd': 'dropped-flag',
        'advisory': 'hrm',
    },
    'OMD_HRM_USER': {
        'd': 'dropped-flag',
        'advisory': 'hrm',
    },
    'ONEDT_ARCHIVE': {
        'd': 'translate',
        't': 'docpath',
    },
    'ONEDT_INBOX': {
        'd': 'translate',
        't': 'docpath',
    },
    'ONEDT_OUTBOX': {
        'd': 'translate',
        't': 'docpath',
    },
    'ONEDT_SENT': {
        'd': 'translate',
        't': 'docpath',
    },
    'ORN_PILOT': {
        'd': 'dropped-flag',
    },
    'PGP_BIN': {
        'd': 'carry',
    },
    'PGP_CMD': {
        'd': 'carry',
    },
    'PGP_ENV': {
        'd': 'carry',
    },
    'PGP_KEY': {
        'd': 'carry-secret',
    },
    'PREVENTION': {
        'd': 'carry',
    },
    'PREVENTION_CLASSIC_VIEW': {
        'd': 'carry',
    },
    'RA_FORWORD': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'RENAL_DOSING_DS': {
        'd': 'carry',
    },
    'RXFAX': {
        'd': 'carry',
    },
    'RX_ALLERGY_CHECKING': {
        'd': 'carry',
    },
    'RX_INTERACTION_LOCAL_DRUGREF_REGIONAL_IDENTIFIER': {
        'd': 'carry',
    },
    'SHOW_FILE_IMPORT_SEARCH': {
        'd': 'carry',
    },
    'SHOW_PREVENTION_STOP_SIGNS': {
        'd': 'carry',
    },
    'SINGLE_PAGE_CHART': {
        'd': 'carry',
    },
    'SOB_CHECKALL': {
        'd': 'carry',
    },
    'SUPERUSER': {
        'd': 'carry',
    },
    'Support_Contact': {
        'd': 'carry',
    },
    'TA_FORWARD': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'TESTING': {
        'd': 'dropped-flag',
    },
    'TIME_FORMAT': {
        'd': 'carry',
    },
    'TOMCAT_KEYSTORE_FILE': {
        'd': 'deploy-owned',
    },
    'TOMCAT_KEYSTORE_PASSWORD': {
        'd': 'deploy-owned',
    },
    'TOMCAT_TRUSTSTORE_FILE': {
        'd': 'deploy-owned',
    },
    'TOMCAT_TRUSTSTORE_PASSWORD': {
        'd': 'deploy-owned',
    },
    'TORONTO_RFQ': {
        'd': 'carry',
    },
    'TRANSPORTATION_TIME_MANDATORY': {
        'd': 'dropped-flag',
    },
    'USE_CAISI_LOGO': {
        'd': 'dropped-flag',
    },
    'USE_NEW_ECHART': {
        'd': 'dropped-flag',
    },
    'USE_NEW_PATIENT_CONSENT_MODULE': {
        'd': 'carry',
    },
    'VMSTAT_LOGGING_PERIOD': {
        'd': 'dropped-flag',
    },
    'Vendor_Product': {
        'd': 'carry',
    },
    'WCB_FORM_REQUIRED_CODES': {
        'd': 'carry',
    },
    'WKHTMLTOPDF_ARGS': {
        'd': 'deploy-owned',
    },
    'WKHTMLTOPDF_COMMAND': {
        'd': 'deploy-owned',
    },
    'admin.hph': {
        'd': 'dropped-flag',
    },
    'allowMultipleSameDayGroupAppt': {
        'd': 'carry',
    },
    'appointment_locking_timeout': {
        'd': 'carry',
    },
    'appt_formTbl': {
        'd': 'carry',
    },
    'appt_intake_form': {
        'd': 'dropped-flag',
    },
    'backup_path': {
        'd': 'deploy-owned',
    },
    'billcenter': {
        'd': 'carry',
    },
    'billregion': {
        'd': 'deploy-owned',
    },
    'buildDateTime': {
        'd': 'deploy-owned',
    },
    'buildtag': {
        'd': 'deploy-owned',
    },
    'carlos.flyway.locations': {
        'd': 'deploy-owned',
    },
    'carlos.flyway.onBoot': {
        'd': 'deploy-owned',
    },
    'casemgmt.note.password.enabled': {
        'd': 'dropped-flag',
    },
    'ckd_notification_scheme': {
        'd': 'dropped-flag',
    },
    'clientdropbox': {
        'd': 'dropped-flag',
    },
    'clinic_no': {
        'd': 'carry',
    },
    'clinic_view': {
        'd': 'carry',
    },
    'cobalt': {
        'd': 'dropped-flag',
    },
    'confidentiality_statement.v1': {
        'd': 'carry',
    },
    'confidentiality_statement.v2': {
        'd': 'carry',
    },
    'consultation_dynamic_labelling_enabled': {
        'd': 'carry',
    },
    'consultation_fax_enabled': {
        'd': 'carry',
    },
    'consultation_signature_enabled': {
        'd': 'carry',
    },
    'contact.required.program': {
        'd': 'dropped-flag',
    },
    'dataCenterId': {
        'd': 'carry',
    },
    'db_driver': {
        'd': 'deploy-owned',
    },
    'db_log_abandoned': {
        'd': 'deploy-owned',
    },
    'db_max_active': {
        'd': 'deploy-owned',
    },
    'db_max_idle': {
        'd': 'deploy-owned',
    },
    'db_max_wait': {
        'd': 'deploy-owned',
    },
    'db_name': {
        'd': 'deploy-owned',
    },
    'db_password': {
        'd': 'deploy-owned',
    },
    'db_remove_abandoned': {
        'd': 'deploy-owned',
    },
    'db_remove_abandoned_timeout': {
        'd': 'deploy-owned',
    },
    'db_type': {
        'd': 'deploy-owned',
    },
    'db_uri': {
        'd': 'deploy-owned',
    },
    'db_username': {
        'd': 'deploy-owned',
    },
    'db_validationQuery': {
        'd': 'deploy-owned',
    },
    'default_bill_center': {
        'd': 'carry',
    },
    'default_search_mode': {
        'd': 'carry',
    },
    'default_view': {
        'd': 'carry',
    },
    'displayAlertsOnScheduleScreen': {
        'd': 'carry',
    },
    'displayNotesOnScheduleScreen': {
        'd': 'carry',
    },
    'documentUploader.maxNumberOfFiles': {
        'd': 'dropped-flag',
    },
    'drugref_route': {
        'd': 'carry',
    },
    'drugref_route_search': {
        'd': 'carry',
    },
    'drugref_url': {
        'd': 'translate',
        't': 'drugref',
    },
    'dxResearch_coding_sys': {
        'd': 'carry',
    },
    'eform_fax_enabled': {
        'd': 'carry',
    },
    'eform_image': {
        'd': 'translate',
        't': 'docpath',
        'as': 'EFORM_IMAGES_DIR',
    },
    'eform_pdf_browser_chromium_path': {
        'd': 'deploy-owned',
    },
    'eform_pdf_browser_service_url': {
        'd': 'deploy-owned',
    },
    'eform_pdf_browser_startup_check': {
        'd': 'deploy-owned',
    },
    'eform_signature_enabled': {
        'd': 'carry',
    },
    'enable_create_child_record': {
        'd': 'dropped-flag',
    },
    'enable_rx_custom_methodone_suboxone': {
        'd': 'dropped-flag',
    },
    'enable_rx_watermark': {
        'd': 'carry',
    },
    'enable_wait_list_email_notifications': {
        'd': 'dropped-flag',
    },
    'encryption.util.secret.key': {
        'd': 'deploy-owned',
    },
    'faxEnable': {
        'd': 'carry',
        'as': 'enableFax',
    },
    'faxIdentifier': {
        'd': 'dropped-flag',
        'advisory': 'fax',
    },
    'faxKeystore': {
        'd': 'dropped-flag',
        'advisory': 'fax',
    },
    'faxLogo': {
        'd': 'dropped-flag',
        'advisory': 'fax',
    },
    'faxPollInterval': {
        'd': 'carry',
    },
    'faxURI': {
        'd': 'dropped-flag',
        'advisory': 'fax',
    },
    'groupModuleEnabled': {
        'd': 'dropped-flag',
    },
    'hl7_a04_build_dir': {
        'd': 'translate',
        't': 'docpath',
    },
    'hl7_a04_fail_dir': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'host': {
        'd': 'deploy-owned',
    },
    'inPatient': {
        'd': 'carry',
    },
    'inactive_statuses': {
        'd': 'carry',
    },
    'isNewONbilling': {
        'd': 'carry',
    },
    'l7_a04_sent_dir': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'lab_req_include_chartno': {
        'd': 'carry',
    },
    'labreq_CKD': {
        'd': 'dropped-flag',
    },
    'log.purge.minDays': {
        'd': 'deploy-owned',
    },
    'log.purge.mysqldump': {
        'd': 'deploy-owned',
    },
    'log.purge.outputdir': {
        'd': 'deploy-owned',
    },
    'login_local_ip': {
        'd': 'carry',
    },
    'login_max_duration': {
        'd': 'carry',
    },
    'login_max_failed_times': {
        'd': 'carry',
    },
    'mandatory_password_reset': {
        'd': 'carry',
    },
    'mcedt.last.downloadedID.file': {
        'd': 'carry',
    },
    'moh_file_management_enabled': {
        'd': 'carry',
    },
    'mrp_model': {
        'd': 'carry',
    },
    'new_flowsheet_enabled': {
        'd': 'carry',
    },
    'new_label_print': {
        'd': 'carry',
    },
    'onare_labreqver': {
        'd': 'carry',
    },
    'ontariomd_cds_diabetes_link': {
        'd': 'dropped-flag',
    },
    'orn_labreqver': {
        'd': 'carry',
    },
    'oscarMeasurement_css': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'oscarMeasurement_css_download_method': {
        'd': 'dropped-flag',
        'advisory': 'misc',
    },
    'oscarMeasurements.orderGroupById': {
        'd': 'carry',
    },
    'oscar_port': {
        'd': 'deploy-owned',
    },
    'phoneprefix': {
        'd': 'carry',
    },
    'prenatal_screening_abbrv': {
        'd': 'carry',
    },
    'prenatal_screening_eform_group': {
        'd': 'carry',
    },
    'prenatal_screening_name': {
        'd': 'carry',
    },
    'prevention_show_comments': {
        'd': 'carry',
    },
    'print.includeMRP': {
        'd': 'carry',
    },
    'print.useCurrentProgramInfoInHeader': {
        'd': 'carry',
    },
    'printPDF_referring_prac': {
        'd': 'carry',
    },
    'professionalContact.required.program': {
        'd': 'dropped-flag',
    },
    'professionalContact.required.workPhone': {
        'd': 'dropped-flag',
    },
    'program': {
        'd': 'carry',
    },
    'project_home': {
        'd': 'deploy-owned',
    },
    'receptionist_alt_view': {
        'd': 'carry',
    },
    'referral_menu': {
        'd': 'carry',
    },
    'resource_base_url': {
        'd': 'carry',
        'validate': 'url',
    },
    'rma_enabled': {
        'd': 'carry',
    },
    'rx.allow_rerx': {
        'd': 'carry',
    },
    'rx.enable_internal_dispensing': {
        'd': 'dropped-flag',
    },
    'rx_enhance': {
        'd': 'carry',
    },
    'rx_fax_enabled': {
        'd': 'carry',
    },
    'rx_signature_enabled': {
        'd': 'carry',
    },
    'rx_strict_med_term': {
        'd': 'carry',
    },
    'save_as_xml': {
        'd': 'carry',
    },
    'schedule.groupsFromPrograms': {
        'd': 'dropped-flag',
    },
    'schedule_templatecode': {
        'd': 'carry',
    },
    'search.most_recent_on_empty': {
        'd': 'carry',
    },
    'search.searchName.addLeadingWildcard': {
        'd': 'carry',
    },
    'searchresults.showAddress': {
        'd': 'carry',
    },
    'seconds_till_considered_stale': {
        'd': 'carry',
    },
    'showBandNumberOnly': {
        'd': 'carry',
    },
    'showRxBandNumber': {
        'd': 'carry',
    },
    'showRxChartNo': {
        'd': 'carry',
    },
    'showSexualHealthLabel': {
        'd': 'carry',
    },
    'skip_postal_code_validation': {
        'd': 'carry',
    },
    'tomcat_path': {
        'd': 'deploy-owned',
    },
    'useDemoClinicInfoOnInvoice': {
        'd': 'carry',
    },
    'use_lab_clientreference': {
        'd': 'carry',
    },
    'version': {
        'd': 'deploy-owned',
    },
    'versionDate': {
        'd': 'deploy-owned',
    },
    'visit_type': {
        'd': 'carry',
    },
    'visitlocation': {
        'd': 'carry',
    },
    'visittype': {
        'd': 'carry',
    },
    'wait_list_email_notification_period': {
        'd': 'dropped-flag',
    },
    'wait_list_email_notification_program_ids': {
        'd': 'dropped-flag',
    },
    'warnOnDeleteBill': {
        'd': 'carry',
    },
    'wl_default_issue': {
        'd': 'carry',
    },
    'workflow_enhance': {
        'd': 'carry',
    },
    'ws_endpoint_url_base': {
        'd': 'deploy-owned',
    },
}

PREFIX_RULES = [
    ('ldap.', {'d': 'dropped-flag', 'advisory': 'ldap'}),
    ('mcedt.', {'d': 'carry-secret'}),
    ('hcv.', {'d': 'carry-secret'}),
    ('email.', {'d': 'carry-secret'}),
    ('teleplan', {'d': 'carry-secret'}),
    ('hibernate.', {'d': 'deploy-owned'}),
    ('db_', {'d': 'deploy-owned'}),
    ('OLIS_', {'d': 'dropped-flag', 'advisory': 'olis'}),
    ('olis_', {'d': 'dropped-flag', 'advisory': 'olis'}),
    ('util.erx.', {'d': 'dropped-flag', 'advisory': 'erx'}),
    ('born', {'d': 'dropped-flag'}),
    ('INTEGRATOR_', {'d': 'dropped-flag'}),
    ('MY_OSCAR', {'d': 'dropped-flag'}),
    ('MYOSCAR', {'d': 'dropped-flag'}),
    ('myoscar', {'d': 'dropped-flag'}),
    ('myOSCAR', {'d': 'dropped-flag'}),
    ('oscar_myoscar', {'d': 'dropped-flag'}),
    ('mymeds', {'d': 'dropped-flag'}),
    ('MYDRUGREF', {'d': 'dropped-flag'}),
    ('CBI_', {'d': 'dropped-flag'}),
    ('clinicaid', {'d': 'dropped-flag'}),
    ('indivica', {'d': 'dropped-flag'}),
    ('consultation_indivica', {'d': 'dropped-flag'}),
    ('eform_generator_indivica', {'d': 'dropped-flag'}),
    ('spire_', {'d': 'dropped-flag'}),
    ('redirectstudysite_', {'d': 'dropped-flag'}),
    ('sharingcenter', {'d': 'dropped-flag'}),
    ('cr_security', {'d': 'dropped-flag'}),
    ('RX3', {'d': 'dropped-flag'}),
    ('loginlogo', {'d': 'dropped-flag'}),
    ('logintext', {'d': 'dropped-flag'}),
    ('logintitle', {'d': 'dropped-flag'}),
    ('eaaps.', {'d': 'dropped-flag'}),
    ('health_tracker', {'d': 'dropped-flag'}),
    ('streethealth', {'d': 'dropped-flag'}),
    ('hsfo', {'d': 'dropped-flag'}),
    ('osp.', {'d': 'dropped-flag'}),
    ('vendor', {'d': 'dropped-flag'}),
    ('software', {'d': 'dropped-flag'}),
    ('lab.handler.', {'d': 'carry'}),
    ('label.', {'d': 'carry'}),
    ('password_', {'d': 'carry'}),
    ('password.', {'d': 'carry'}),
    ('tickler', {'d': 'carry'}),
    ('caisi.', {'d': 'carry'}),
    ('pmm.', {'d': 'carry'}),
    ('multioffice.', {'d': 'carry'}),
    ('QR_CODE_', {'d': 'carry'}),
    ('refresh.', {'d': 'carry'}),
    ('web_service_client.', {'d': 'carry'}),
    ('form_intake_program_', {'d': 'carry'}),
    ('DEMOGRAPHIC_CONTACT', {'d': 'carry'}),
    ('invoice_', {'d': 'carry'}),
    ('billing', {'d': 'carry'}),
]
